### PR TITLE
Fixed issue #27: replace dev PURLs; and recategorized 'US Census trac…

### PR DESCRIPTION
**Pull request by dillerm**
…t region role', 'US county region role', and 'US state region role'.

### CODE REVIEW

**Comment by hoganwr** [comment]
For some reason, lake, sea, and ocean have redundant classes with different PURLs.
Screenshot 2024-02-07 at 8 37 56 AM

That might be a pre-existing issue, which requires a separate issue to be logged and fixed at another time, however.

**Comment by hoganwr** [comment]
Although we removed 'deontic role' as a parent, the class definitions still mention it, of US census tract region role, US state region role, and US county region role.

**Comment by dillerm** [comment]
@hoganwr what file are you seeing those duplicates in?

**Comment by hoganwr** [comment]
I believe it was geo.all

**Comment by hoganwr** [comment]
also do you plan to fix the textual definitions as I mentioned above?

**Comment by dillerm** [comment]
Yes, I already have fixed them in my local copy of us-integral-geography.owl.

**Pull request merged**
