### PR TITLE
Created OWL individuals for Florida Census tracts.

### PR DESCRIPTION
**Pull request by dillerm**

### CODE REVIEW

**Comment by hoganwr** [comment]
I don't see any annotation on the individuals that provides the Census codes for the Census tract.  Aren't they coded according to a code that has the format <state FIPS><county FIPS><tract number>.  For example: 12001000201

We might need a new annotation property for it: INCITS 31 is strictly limited to counties. 

It looks like the Census formally calls them GEOID: https://www.census.gov/programs-surveys/geography/guidance/geo-identifiers.html

**Comment by dillerm** [comment]
**Proposed label:** US Census Bureau geographical identifier
**Editor preferred term:** US Census GEOID
**Definition:** An annotation property to identify OWL 2 individuals that represent geographical entities with their appropriate US Census-designated geographical identifier.

**Comment by hoganwr** [comment]
Propose to swap the label & editor preferred term

**Comment by dillerm** [comment]
Should this go in geo.owl or a different file? This is where we have the other annotations, like 'admin1 code' and 'US State Two Digit Identifier'.

**Comment by dillerm** [comment]
GEOIDs have been added.

**Comment by hoganwr** [comment]
Looks good!  Can merge.

**Pull request merged**
